# Generated by Django 4.2.28 on 2026-02-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
    ]
