# Generated by Django 5.0.3 on 2026-02-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20260227_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'models_district',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'models_state',
            },
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='volunteer_count',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='area_type_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='education_field',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='education_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='maritalstatus_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='salutation_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='state_id',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.organization'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.district'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TECHNICAL_ADMIN', 'Technical Admin'), ('NDMA_ADMIN', 'NDMA Admin'), ('SDMA_ADMIN', 'SDMA Admin'), ('DDMA_NODAL_OFFICER', 'DDMA Nodal Officer'), ('TRAINING_INSTITUTE', 'Training Institute'), ('YOUTH_ORG_ADMIN', 'Youth Organisation Admin'), ('VOLUNTEER', 'Volunteer'), ('PUBLIC_USER', 'Public User')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('hierarchy_level', models.IntegerField(default=0)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='models.permission')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['hierarchy_level'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_permission_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='models.state'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.state'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mfa_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='models.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
