# Generated by Django 5.0.3 on 2026-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_add_volunteer_count_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='area_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Urban'), (2, 'Rural'), (3, 'Semi-Urban')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='education_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='education_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Below 10th'), (2, '10th Pass'), (3, '12th Pass'), (4, 'Diploma'), (5, 'Bachelor'), (6, 'Master'), (7, 'PhD'), (8, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='maritalstatus_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Separated')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='salutation_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.'), (5, 'Prof.')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skill_id',
            field=models.IntegerField(blank=True, choices=[(1, 'First Aid'), (2, 'Disaster Management'), (3, 'Rescue Operations'), (4, 'Community Care'), (5, 'Training'), (6, 'Other')], null=True),
        ),
    ]
