# Generated by Django 5.0.3 on 2026-03-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_volunteer_area_type_id_volunteer_education_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_code',
        ),
        migrations.AddField(
            model_name='user',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='models.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='models.state'),
        ),
    ]
