# Generated by Django 4.2.28 on 2026-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_role_is_system_role_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='lgd_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='lgd_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
