# Generated by Django 5.0.3 on 2026-03-01 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_district_lgd_code_state_lgd_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_type', models.CharField(choices=[('NCC', 'NCC'), ('NSS', 'NSS'), ('YOUTH_ORG', 'Youth Organisation'), ('INSTITUTE', 'Institute'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('number_of_volunteers', models.PositiveIntegerField(default=0)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('institute_details', models.TextField(blank=True, null=True)),
                ('trainers_details', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('upload_option', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_schedules', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_schedules', to='models.district')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_schedules', to='models.state')),
            ],
            options={
                'db_table': 'models_training_schedule',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('upload_option', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='models.trainingschedule')),
            ],
            options={
                'db_table': 'models_training_session',
            },
        ),
    ]
