# Generated by Django 5.0.3 on 2026-03-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_organizationtype_and_update_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTypeChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area Type Choice',
                'verbose_name_plural': 'Area Type Choices',
                'db_table': 'models_area_type_choice',
            },
        ),
        migrations.CreateModel(
            name='BloodGroupChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blood Group Choice',
                'verbose_name_plural': 'Blood Group Choices',
                'db_table': 'models_bloodgroup_choice',
            },
        ),
        migrations.CreateModel(
            name='EducationChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education Choice',
                'verbose_name_plural': 'Education Choices',
                'db_table': 'models_education_choice',
            },
        ),
        migrations.CreateModel(
            name='GenderChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gender Choice',
                'verbose_name_plural': 'Gender Choices',
                'db_table': 'models_gender_choice',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatusChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marital Status Choice',
                'verbose_name_plural': 'Marital Status Choices',
                'db_table': 'models_maritalstatus_choice',
            },
        ),
        migrations.CreateModel(
            name='SalutationChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salutation Choice',
                'verbose_name_plural': 'Salutation Choices',
                'db_table': 'models_salutation_choice',
            },
        ),
        migrations.CreateModel(
            name='SkillChoice',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Choice',
                'verbose_name_plural': 'Skill Choices',
                'db_table': 'models_skill_choice',
            },
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='area_type_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='bloodgroup_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='education_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='gender_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='maritalstatus_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mybharat_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='salutation_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skill_id',
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='models.organizationtype'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='area_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.areatypechoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bloodgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.bloodgroupchoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.educationchoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.genderchoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='maritalstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.maritalstatuschoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers_salutation', to='models.salutationchoice'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='models.skillchoice'),
        ),
    ]
