# Generated by Django 5.0.3 on 2026-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_areatypechoice_bloodgroupchoice_educationchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='maritalstatus',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skill',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='area_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Urban'), (2, 'Rural'), (3, 'Semi-Urban')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bloodgroup_id',
            field=models.IntegerField(blank=True, choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='education_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Below 10th'), (2, '10th Pass'), (3, '12th Pass'), (4, 'Diploma'), (5, 'Bachelor'), (6, 'Master'), (7, 'PhD'), (8, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='maritalstatus_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Separated')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='mybharat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='salutation_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.'), (5, 'Prof.')], null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skill_id',
            field=models.IntegerField(blank=True, choices=[(1, 'First Aid'), (2, 'Disaster Management'), (3, 'Rescue Operations'), (4, 'Community Care'), (5, 'Training'), (6, 'Other')], null=True),
        ),
    ]
