# Generated by Django 6.0.2 on 2026-03-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_trainingschedule_trainingsession'),
        ('models', '0007_organization_updates'),
    ]

    operations = [
    ]
