# Generated by Django 5.0.3 on 2026-03-06 05:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_volunteer_area_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_sessions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='models.trainingsession')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_training_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session Media',
                'verbose_name_plural': 'Training Session Media',
                'db_table': 'models_training_session_media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
