# Generated by Django 5.0.3 on 2026-03-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_trainingsessionmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='mis_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
